const TOPICS = [
['Marketing foundations',[
['Market orientation','Organization-wide generation, sharing and response to market intelligence','selling orientation, which starts with what the firm already makes','A steel producer aligns product, service and investment decisions around changing customer and competitor insight.','Build cross-functional routines that sense and respond to chosen markets.'],
['Value delivery process','Choosing value, providing value and communicating value in sequence','promotion, which communicates but does not create the whole value proposition','A mill launches advertising before deciding target customers or the operational promise.','Return to STP before configuring and communicating the offering.'],
['Holistic marketing','Internal, integrated, relationship and performance marketing considered together','a campaign-only view of marketing','Commercial promises fail because operations, channel partners and incentives are misaligned.','Manage marketing as an enterprise system, not a communications department.'],
['Selling orientation','An inside-out emphasis on pushing what the firm has produced','market orientation, which starts from selected customer needs','Management responds to excess commodity inventory only by raising sales targets and discounts.','Diagnose demand and value before intensifying the sales push.']]],
['Planning & G-STIC',[
['G-STIC','Goal, Strategy, Tactics, Implementation and Control','a budget calendar without explicit goals or strategic logic','A business has campaign activities but no quantified objective, target or value proposition.','Link every action and metric back to a defined goal and strategy.'],
['Marketing strategy','The target market and value proposition chosen to achieve a goal','marketing tactics, the specific product, communication and channel actions','A leader debates dealer incentives before selecting priority segments.','Set target and value proposition before deciding execution levers.'],
['Implementation','Organizing resources, processes and accountability to execute strategy','strategy formulation, which defines where and how to compete','A sound key-account strategy stalls because roles, capability and milestones are absent.','Translate choices into owners, resources, timing and interdependencies.'],
['Marketing control','Comparing outcomes with goals and taking corrective action','reporting metrics without decision thresholds','A dashboard shows lead volume but no owner acts when qualified conversion falls.','Predefine metrics, thresholds, review cadence and corrective actions.']]],
['Customer value & loyalty',[
['Customer-perceived value','The difference between total customer benefits and total customer costs','low price alone, which ignores non-price benefits and costs','An automotive buyer accepts a higher steel price because yield, reliability and technical support lower total cost.','Frame value in the customer’s economics, not only the supplier’s product claims.'],
['Customer satisfaction','A judgement formed by comparing perceived performance with expectations','loyalty, which is repeat preference and behavior over time','A buyer rates delivery highly but switches after a rival offers a superior bundle.','Treat satisfaction as necessary but not sufficient for loyalty.'],
['Customer loyalty','A deeply held commitment to rebuy despite alternatives and situational pressure','inertia caused only by switching barriers','A fabricator repeatedly specifies a brand and advocates it despite cheaper quotes.','Measure retention, share of wallet and advocacy, not satisfaction alone.'],
['Customer profitability','Revenue from a customer minus the full cost of attracting, serving and retaining that customer','market share, which aggregates volume regardless of account economics','A large account demands custom batches, long credit and frequent emergency shipments.','Manage account economics and strategic potential, not revenue rank alone.']]],
['STP',[
['Segmentation','Dividing a market into meaningfully distinct groups with different needs or responses','targeting, which evaluates and selects segments','A steel firm groups fabricators by application, buying criteria and service sensitivity.','Use variables that predict different needs and responses, not convenient labels.'],
['Targeting','Evaluating segment attractiveness and choosing which segments to serve','positioning, which defines the intended place in the target customer’s mind','A manufacturer ranks infrastructure, auto and SME segments by fit, growth and economics.','Choose deliberately; serving every segment usually weakens fit and resource focus.'],
['Positioning','Designing the offering and image to occupy a distinctive, valued place for a target','product differentiation, which creates real differences but not necessarily perceived meaning','Buyers see technically superior steel as interchangeable with competitors.','Clarify the target, frame of reference, points of difference and reasons to believe.'],
['Points of parity and difference','Necessary category associations plus unique, credible and relevant benefits','a long undifferentiated feature list','A coated-steel offer must first meet industry standards, then own a corrosion-life advantage.','Establish category legitimacy before emphasizing a defensible difference.']]],
['Consumer behaviour',[
['Consumer decision journey','Problem recognition, information search, evaluation, purchase and post-purchase behavior','a linear sales funnel that ends at purchase','A homeowner researches roofing brands online, asks contractors and later posts a review.','Design connected interventions before, during and after purchase.'],
['Perceived risk','Expected negative consequences and uncertainty surrounding a choice','low awareness, which concerns memory rather than feared outcomes','Home builders avoid an unfamiliar premium material despite strong specifications.','Reduce functional, financial and social uncertainty with proof and guarantees.'],
['Reference groups','Groups that directly or indirectly influence attitudes or behavior','personal demographics alone','Architect recommendations shift homeowners toward a branded building material.','Map who influences, decides, buys and uses—not only who pays.'],
['Post-purchase dissonance','Doubt or discomfort after a consequential choice','problem recognition before purchase','After choosing a costly roof, a buyer seeks reassurance that alternatives were inferior.','Reinforce the decision with onboarding, evidence and service.']]],
['Organizational buying',[
['Buying center','All participants sharing roles in an organizational purchase decision','the purchasing department alone','Quality, production, finance, procurement and plant leadership jointly assess a new grade.','Tailor evidence to users, influencers, deciders, buyers and gatekeepers.'],
['Buygrid situations','Straight rebuy, modified rebuy and new task purchases requiring different effort','consumer adoption categories','A customer reorders a standard grade versus qualifying a new lightweight alloy.','Match sales resources and information depth to purchase novelty and risk.'],
['Derived demand','Business demand that ultimately derives from demand for downstream products','independent demand created solely by supplier promotion','Auto slowdown reduces steel orders even when the supplier’s share is stable.','Monitor customers’ end markets and leading indicators, not only direct orders.'],
['Solution selling','Diagnosing a business problem and configuring integrated value around outcomes','product pitching based on specifications alone','A sales team combines grade choice, process advice and logistics to cut scrap.','Quantify operational and financial outcomes across stakeholders.']]],
['Research & intelligence',[
['Marketing research process','Define the problem, develop the plan, collect and analyze data, present findings and decide','starting with a preferred survey method','Management asks whether falling conversion reflects price, lead quality or service.','Define the decision and alternatives before collecting data.'],
['Marketing intelligence','Ongoing information about developments in the marketing environment','a one-time commissioned research project','A team continuously tracks tender activity, competitor capacity and dealer sentiment.','Build ethical, repeatable sensing routines that feed decisions.'],
['Causal research','Testing whether a change in one factor produces a change in another','descriptive research that measures association or prevalence','A firm pilots two price architectures in comparable territories.','Use controlled variation and guard against confounds before claiming causality.'],
['Data triangulation','Combining methods and sources to test whether conclusions converge','trusting a single dashboard because it is quantitative','Dealer interviews conflict with CRM win-loss codes and shipment data.','Reconcile behavioral, attitudinal and operational evidence before acting.']]],
['Customer journey',[
['Touchpoint mapping','Identifying customer interactions across pre-purchase, purchase and post-purchase stages','listing only paid media channels','A fabricator encounters search, technical sales, sampling, delivery and claims support.','Manage the end-to-end experience across functions and channel owners.'],
['Moments of truth','Interactions disproportionately shaping customer perceptions and relationship outcomes','every routine contact weighted equally','The first complaint resolution determines whether a key account expands the relationship.','Prioritize high-emotion, high-risk interactions and empower recovery.'],
['Omnichannel consistency','A coordinated experience and data flow across channels','simply operating many independent channels','A buyer gets different prices and promises from portal, salesperson and distributor.','Integrate rules, data and handoffs while preserving useful channel roles.'],
['Friction diagnosis','Finding unnecessary effort that blocks progress through a journey','adding communications without fixing process barriers','Qualified B2B leads abandon a portal requiring repeated technical data entry.','Remove customer effort at the constraint before buying more traffic.']]],
['Brand fundamentals',[
['Brand identity','The intended meaning and associations the firm seeks to create','brand image, the associations customers actually hold','Leadership intends innovation while customers describe the brand as traditional.','Measure the identity–image gap and change experience as well as communication.'],
['Brand awareness','The strength of recognition and recall in buying situations','brand equity, the broader differential effect of brand knowledge','Most fabricators know a steel brand but do not prefer or pay more for it.','Awareness creates consideration; it does not prove meaning, response or loyalty.'],
['Brand equity','The differential customer response caused by brand knowledge','financial brand valuation, a monetary estimate of the brand asset','Identical offers receive different preference because one carries a trusted name.','Track how brand knowledge changes choice, price response and behavior.'],
['Brand mantra','A short internal articulation of the brand’s core promise and spirit','an external advertising slogan','Teams need a compact filter for judging extensions and customer experiences.','Use it internally to discipline decisions, not as decorative copy.']]],
['CBBE & resonance',[
['Brand salience','How easily and broadly the brand is identified across purchase and usage situations','brand resonance, the apex relationship outcome','A brand is recalled only by existing industrial buyers in one application.','Build both depth and breadth of awareness before expecting stronger responses.'],
['Brand performance and imagery','Functional delivery and the extrinsic meaning customers attach to the brand','judgments and feelings, which are customer responses to that meaning','Buyers assess metallurgical consistency while associating the brand with modern engineering.','Build rational performance and relevant imagery as parallel meaning routes.'],
['Brand judgments and feelings','Customers’ evaluations and emotional responses to brand meaning','salience, which concerns identification and recall','A brand is seen as credible and superior and makes specifiers feel professionally secure.','Convert meaning into credible quality judgments and context-relevant emotion.'],
['Brand resonance','Intense active loyalty expressed through behavior, attachment, community and engagement','repeat purchase driven only by a contract','Fabricators advocate a brand, join technical forums and resist competitor inducements.','The apex is an active relationship, not awareness or repeat sales alone.']]],
['Positioning & differentiation',[
['Frame of reference','The category or competitive set that tells customers what the offer is and why it matters','the target segment itself','A new composite competes as a steel substitute rather than merely as another composite.','Choose the frame because it determines relevant parity and difference.'],
['Functional differentiation','Superior performance on attributes or outcomes customers value','image differentiation based mainly on symbolic associations','A grade reduces component weight while maintaining strength.','Prove the benefit in customer operations and protect its credibility.'],
['Emotional differentiation','Creating valued feelings, identity or reassurance beyond functional performance','feature superiority alone','A building-material brand gives homeowners pride and confidence in durability.','Use emotion when it is authentic to the category experience and supported by delivery.'],
['Competitive advantage','An ability to perform in ways competitors cannot or will not match','a temporary message unsupported by capabilities','Fast custom-grade development rests on proprietary know-how and integrated customer teams.','Position around advantages that are valuable, deliverable and difficult to neutralize.']]],
['Brand architecture',[
['Brand elements','Names, logos, symbols, characters, slogans and other identifiers','product features that are not brand identifiers','A new industrial service needs memorable, meaningful and transferable identifiers.','Select elements for memorability, meaning, appeal, transferability, adaptability and protection.'],
['Brand extension','Using an established brand to launch in a new category','a line extension within the same category','A trusted steel brand enters prefabricated construction solutions.','Assess parent fit, extension advantage and reciprocal equity effects.'],
['Line extension','Using an existing brand for a new variant in its current category','a new brand in a new category','A coated-steel brand adds thicknesses for another use case.','Use variants to cover real needs without creating confusion or cannibalization.'],
['Brand portfolio','The set of brands and roles a firm manages across markets','a list of SKUs under one product line','A company balances corporate, premium, fighter and regional brands.','Give each brand a distinct role and eliminate costly overlap.']]],
['Product & line strategy',[
['Product levels','Core benefit, basic, expected, augmented and potential product','a feature hierarchy based only on engineering','For industrial steel, continuity of production may be the core benefit while technical service augments it.','Define the offer from the customer’s job outward.'],
['Product-line depth','The number of variants offered within a product line','product-mix width, the number of different lines','A producer adds grades and gauges within automotive steel.','Add depth only when incremental demand and strategic coverage exceed complexity cost.'],
['Line stretching','Extending a line downward, upward or both beyond its current range','line filling within the current range','A premium industrial brand launches an economy tier for smaller fabricators.','Anticipate cannibalization, brand dilution and channel conflict before stretching.'],
['Product-line pruning','Removing weak or strategically distracting items','automatic retention of every revenue-generating SKU','Long-tail grades consume setups and inventory while generating little contribution.','Evaluate full complexity-adjusted profit and customer migration options.']]],
['Innovation & NPD',[
['Stage-gate development','Advancing ideas through defined evidence-based decision gates','an unstructured launch-first innovation process','A new alloy progresses from idea validation to concept, business model, implementation and deployment.','Increase commitment as uncertainty falls; kill weak ideas early.'],
['Concept testing','Testing a product idea expressed in meaningful consumer terms before full development','product testing of a finished physical prototype','Potential buyers evaluate a proposed low-carbon steel solution and its benefits.','Test customer understanding, relevance, believability and purchase response early.'],
['Business-model validation','Testing how the offering creates, delivers and captures value','technical validation of product performance alone','A service concept is attractive, but willingness to pay and delivery economics remain unknown.','Validate customer desirability, operational feasibility and economic viability together.'],
['Innovation adoption','Relative advantage, compatibility, complexity, divisibility and communicability shape adoption','launch awareness as the only adoption driver','Fabricators value a new grade but qualification cost and process change slow uptake.','Reduce adoption friction and make trial and results observable.']]],
['Product life cycle',[
['Introduction stage','Low initial sales, high market-development effort and uncertain adoption','maturity, where rivalry and market saturation dominate','A new industrial material needs education, qualification and reference users.','Optimize learning and adoption, not premature volume efficiency.'],
['Growth stage','Rapid acceptance, rising competition and opportunities to build preference and distribution','decline, where demand contracts structurally','Demand accelerates and rivals enter with similar value propositions.','Improve the offer, expand access and reinforce differentiation before imitation catches up.'],
['Maturity stage','Slowing growth, high penetration and intensified share competition','introduction, where category education is primary','A standard grade faces stable demand, broad availability and price pressure.','Defend profitable segments, improve efficiency and seek meaningful modification.'],
['Decline management','Harvesting, maintaining, repositioning or divesting as demand falls','automatic discounting to preserve unit volume','A legacy material loses applications to substitutes and consumes specialist capacity.','Separate temporary weakness from structural decline, then allocate capital explicitly.']]],
['Pricing strategy',[
['Value-based pricing','Setting price from customer-perceived value and economics','cost-plus pricing, which starts with seller cost and markup','A higher-grade steel reduces scrap and downtime enough to justify a premium.','Quantify and communicate the customer’s economic value while retaining a fair share.'],
['Economic value to customer','The reference alternative plus the monetary value of performance differences','the supplier’s production cost','A coating adds years of asset life and avoids maintenance shutdowns.','Anchor the premium in documented customer savings and risk reduction.'],
['Price segmentation','Varying price by legitimate differences in value, segment or transaction conditions','indiscriminate discounting to close every deal','Urgent small lots and predictable annual contracts create different service economics.','Use transparent fences that reflect value or cost-to-serve.'],
['Price waterfall','The sequence from list price through discounts, allowances and leakage to pocket price','average list-price movement alone','Headline prices rise while rebates, freight and payment terms erase realization.','Govern every leakage point and track pocket margin by account and transaction.']]],
['Channels & distribution',[
['Channel design','Choosing intermediaries, responsibilities and structure to deliver target-customer value','selecting partners only by current sales volume','A steel firm must balance direct key accounts, distributors and digital ordering.','Start with customer service outputs, then assign channel roles and economics.'],
['Push strategy','Using sales force and trade incentives to move offerings through intermediaries','pull strategy, which stimulates end-customer demand','A manufacturer trains dealers and rewards stocking of a new branded product.','Use push when channel recommendation, availability and sell-through are decisive.'],
['Pull strategy','Creating end-user demand so customers request the brand through the channel','trade loading without customer demand','Architect campaigns cause homeowners to ask dealers for a branded roofing product.','Ensure supply and partner economics can fulfill demand the brand creates.'],
['Channel conflict','Disagreement among channel members over roles, goals or rewards','healthy competition with clear rules','Direct digital quotes undercut distributors serving the same SME customers.','Clarify account ownership, pricing rules, service credit and conflict resolution.']]],
['Retail, wholesale & GTM',[
['Go-to-market model','The coordinated system for reaching, selling to and serving chosen customers','a distribution coverage target alone','A producer redesigns account roles, partners, digital journeys, service and economics by segment.','Align coverage, selling motion, fulfillment and incentives with segment needs.'],
['Intensive distribution','Making an offering available through as many suitable outlets as possible','exclusive distribution through one or few partners','A standardized high-frequency building input depends on convenient local availability.','Choose intensity based on buying convenience, control needs and channel economics.'],
['Selective distribution','Using more than one but fewer than all willing intermediaries','intensive distribution with minimal qualification','A technical product requires trained dealers yet customers need reasonable geographic access.','Trade some reach for competence, economics and experience control.'],
['Channel productivity','Outputs and profitable growth generated relative to channel resources and cost','distribution coverage, the number or geographic spread of outlets','A distributor network expands outlet count while active selling and contribution per outlet fall.','Measure activation, sell-through, service and contribution—not footprint alone.']]],
['Integrated communications',[
['IMC','Coordinating messages and media so the brand speaks clearly and consistently','using the same creative asset everywhere regardless of channel role','Technical sales, PR, digital content and dealer material reinforce one value proposition.','Integrate the idea and customer journey while adapting execution to each medium.'],
['Communication objectives','Category need, awareness, attitude and purchase intention outcomes','media activity counts such as impressions alone','A known industrial brand must shift perceptions of innovation, not merely increase reach.','Define the customer response required before choosing message and media.'],
['Message strategy','What to say and how to connect the brand with relevant value','media strategy, which decides where and when exposure occurs','A campaign must translate lower lifecycle cost into a credible decision argument.','Match message content, proof and creative execution to the objective.'],
['Communication measurement','Assessing reach, response, brand effects and behavioral or financial outcomes','equating last-click attribution with total incremental impact','Brand search rises, but management needs evidence that the campaign changed qualified demand.','Use a measurement design matched to the objective and separate incrementality from attribution.']]],
['Media, PR & digital',[
['Advertising','Paid nonpersonal presentation by an identified sponsor','publicity, which is earned and not fully controlled','A brand buys targeted video and trade-media placements to build consideration.','Use advertising for scalable, controlled reach and repetition.'],
['Sales promotion','Short-term incentives designed to stimulate trial or purchase','durable positioning, which should survive temporary incentives','A dealer scheme accelerates orders but customers wait for the next discount.','Use promotion for a defined behavioral job and guard against reference-price damage.'],
['Public relations','Programs that promote or protect organizational and brand reputation','paid media with complete message control','Independent coverage of verified sustainability progress builds stakeholder credibility.','Earn trust through newsworthy proof; PR cannot compensate for weak substance.'],
['Digital attribution','Assigning conversion credit across measurable interactions','causal incrementality, which estimates what would not have happened otherwise','A retargeting ad claims a sale after salespeople and search created demand.','Treat attribution as a model of credit, then test incrementality before reallocating spend.']]],
['Personal selling & sales force',[
['Consultative selling','Discovering needs and co-creating a solution rather than leading with a pitch','transactional order taking','A seller investigates the customer’s yield loss before recommending a steel grade.','Earn the right to propose by diagnosing value drivers and stakeholders.'],
['Sales-force structure','Organizing sellers by geography, product, market or a hybrid','setting individual quotas without clarifying coverage roles','Key automotive accounts need industry expertise while SMEs need efficient territory coverage.','Choose structure around customer complexity, specialization and coordination cost.'],
['Sales compensation','Combining pay and incentives to direct effort toward desired outcomes','rewarding volume regardless of margin, mix or retention','Representatives discount heavily because incentives reward tonnes sold only.','Align measures with profitable growth while avoiding an unmanageable scorecard.'],
['Key-account management','Coordinating long-term, cross-functional value creation for strategically important accounts','giving every large customer maximum concessions','A major OEM relationship spans innovation, quality, logistics and senior governance.','Select accounts by strategic value and mutual potential, then build joint plans.']]],
['CRM & relationship marketing',[
['Relationship marketing','Building mutually valuable long-term relationships with key stakeholders','retention through lock-in alone','A supplier invests in joint process improvement and shared planning with fabricators.','Create reasons to stay through superior mutual value, trust and commitment.'],
['CRM','Managing detailed customer information and touchpoints to improve relationships and economics','a software database without processes or adoption','Account history exists, but service and sales teams cannot coordinate next actions.','Make data actionable through ownership, workflows and customer-value decisions.'],
['Share of customer','The proportion of a customer’s category purchases captured by the firm','market share across all customers','A supplier grows within selected accounts without expanding category-wide volume.','Use cross-sell and deeper relevance where account potential and profitability justify it.'],
['Service recovery','Resolving failures fairly and rapidly to restore confidence','silencing complaints to protect satisfaction scores','A late shipment stops a customer line and threatens a strategic relationship.','Own the impact, recover operations, communicate and eliminate root cause.']]],
['CLV & profitability',[
['Customer lifetime value','The discounted stream of expected future customer contribution net of acquisition and service costs','current-year customer revenue','An account’s first order is small but repeat potential, retention and margin are strong.','Allocate acquisition and retention investment against risk-adjusted future contribution.'],
['Retention economics','The effect of churn, margin, service cost and duration on customer value','a universal claim that retention is always cheaper than acquisition','Some low-margin accounts consume escalating support and have little growth potential.','Retain selectively; loyalty without positive economics destroys value.'],
['Customer equity','The sum of discounted lifetime values of the customer base','brand valuation based on royalty or financial approaches','Management evaluates how acquisition, retention and margin choices change future customer cash flows.','Connect marketing actions to the value and risk of the customer portfolio.'],
['Cost to serve','All activity and resource costs required to support an account or segment','manufacturing cost alone','Two equal-revenue distributors differ sharply in order variability, credit and service demands.','Use activity-based insight to manage terms, service models and account profitability.']]],
['Competition & growth',[
['Market leader strategy','Expanding total demand while defending and growing share','challenger strategy based primarily on attacking an incumbent','The largest supplier develops new uses and protects vulnerable segments.','Balance category expansion with focused defense; do not defend every position equally.'],
['Market challenger strategy','Gaining share through a clear objective and focused attack','follower strategy that avoids provoking the leader','A smaller producer attacks an underserved service weakness rather than matching the leader broadly.','Concentrate superior resources on a consequential vulnerability.'],
['Market follower strategy','Maintaining differentiation and profitability while avoiding costly direct challenge','passive imitation with no customer value','A regional player serves selected niches efficiently without triggering broad retaliation.','Follow selectively, retain distinct value and protect economics.'],
['Ansoff growth logic','Market penetration, market development, product development and diversification','growth measured only as higher volume in existing products and markets','A steel business weighs deeper current-account share against new applications and adjacencies.','Name which product–market risk is being added before funding growth.']]],
['Metrics & ROI',[
['Marketing ROI','Incremental financial return attributable to marketing investment relative to its cost','revenue divided by marketing spend without a counterfactual','A campaign generated sales, but baseline demand and margin are not separated.','Estimate incrementality and contribution, state the time horizon and include relevant costs.'],
['Leading indicators','Metrics that signal future outcomes before financial results appear','lagging outcomes such as realized revenue','Qualified pipeline, trial completion and specification wins precede industrial sales.','Use leading indicators for intervention and lagging indicators for outcome accountability.'],
['Market share','Firm sales relative to relevant market sales','customer profitability, which measures account-level economics','Volume share rises through deeply discounted low-margin contracts.','Read share with price, mix, margin and market definition; share is not the objective by itself.'],
['Dashboard design','A focused set of linked metrics supporting decisions and accountability','a data dump containing every available KPI','Executives see dozens of metrics without targets, drivers or action owners.','Connect goal, driver, outcome, threshold and owner in a decision hierarchy.']]],
['Data-driven marketing',[
['Predictive analytics','Using data patterns to estimate likely future behavior or outcomes','descriptive analytics reporting what happened','A model ranks leads by likelihood of qualification and expected account value.','Use predictions to improve a specified decision and monitor drift and bias.'],
['Personalization','Adapting content, offer or experience using relevant customer data','mass communication with a first-name token','A portal changes technical recommendations based on application and purchase history.','Personalize only where relevance improves enough to justify data and complexity costs.'],
['Experimentation','Comparing controlled variants to estimate causal impact','observing correlations after an uncontrolled campaign','Territories are randomized to alternative lead-nurture programs.','Predefine outcome, unit, sample and guardrails before seeing results.'],
['Privacy stewardship','Collecting and using customer data transparently, securely and proportionately','maximizing data capture because consent was technically obtained','A B2B platform requests sensitive operational data unrelated to current value.','Earn trust through purpose limitation, minimization, control and security.']]],
['Sustainability & responsibility',[
['Societal marketing concept','Balancing customer wants, company requirements and society’s long-run interests','short-term customer satisfaction regardless of externalities','Demand favors cheap material while lifecycle emissions and safety matter societally.','Integrate customer value, business viability and long-term welfare in the offer.'],
['Sustainability positioning','Making a relevant, distinctive and credible sustainability benefit part of value','green claims disconnected from customer benefit or proof','Lower-carbon steel offers tender eligibility and downstream footprint reduction with verified data.','Tie environmental performance to target value and substantiate every claim.'],
['Cause marketing','Linking company contributions to customer engagement in a cause','social marketing aimed primarily at changing public behavior','A brand donates per purchase to a relevant community program.','Ensure strategic fit, transparency and real impact rather than borrowed virtue.'],
['Ethical marketing','Applying fairness, honesty and stakeholder responsibility to marketing decisions','mere legal compliance at the boundary of acceptable conduct','A seller could exploit opaque surcharges that customers cannot evaluate.','Protect long-term trust by making value, price and evidence intelligible and fair.']]],
['Head-level integration',[
['Profitable growth','Growth that improves sustainable contribution and enterprise value','volume growth regardless of price, mix, capital or service burden','Tonnes rise but discount leakage, working capital and low-value mix destroy return.','Decompose growth into volume, price, mix, retention, cost-to-serve and capital effects.'],
['Commercial operating model','The integrated design of marketing, sales, service, data, governance and incentives','a reorganization of reporting lines alone','Strategy changes toward solutions, but quotas, skills, CRM and decision rights remain product-led.','Align capabilities and management systems with the chosen way to win.'],
['Portfolio resource allocation','Shifting resources across segments, offers and channels according to strategic return and risk','spreading budget evenly to avoid internal conflict','A mature commodity line funds growth while value-added segments need capability investment.','Use explicit roles, horizons and risk-adjusted economics—not historical entitlement.'],
['Strategic trade-off','A deliberate choice that concentrates advantage by declining incompatible activities','trying to maximize reach, customization, speed and low cost simultaneously','A business must choose tailored key-account service or uniform low-cost coverage by segment.','Make trade-offs visible; strategy is what the company chooses not to do.']]]
];

const LETTERS=['A','B','C','D'];
const contexts=['steel and metals','industrial products','automotive supply','construction materials','manufacturing services','distribution networks'];
const commonDistractors=['Maximize short-term volume before clarifying the customer problem.','Copy the market leader’s visible tactics without testing strategic fit.','Treat one activity metric as proof of long-term customer value.'];
function makeQuestions(){const out=[];TOPICS.forEach((topic,ti)=>topic[1].forEach((c,ci)=>{
 const [name,definition,contrast,scenario,action]=c, n=ti*4+ci;
 const wrong=[`Prioritize ${contrast}.`,...commonDistractors].slice(0,3);
 const others=[1,2,3].map(offset=>topic[1][(ci+offset)%4]);
 const explanation=`${name} means ${definition}. The other choices describe ${contrast}, imitate activity without strategic fit, or mistake a partial metric for customer value.`;
 const variants=[
 {difficulty:'Intermediate',type:'single',q:`Which statement best captures ${name}?`,correct:[0],opts:[definition,contrast,commonDistractors[2],commonDistractors[1]],why:explanation},
 {difficulty:n%5<4?'Fundamental':'Intermediate',type:'truefalse',q:`True or false: ${name} should be understood as ${definition}.`,correct:[0],opts:['True','False'],why:`True. ${name} is ${definition}. False would confuse it with ${contrast}.`},
 {difficulty:n%5===0?'Intermediate':'Applied',type:'single',q:`In ${contexts[(ti+ci)%contexts.length]}, management faces this situation: ${scenario} What is the most relevant concept?`,correct:[0],opts:[name,...others.map(x=>x[0])],why:`${name} directly fits because it concerns ${definition}. ${others.map(x=>`${x[0]} instead addresses ${x[1]}`).join('; ')}.`},
 {difficulty:n%5<2?'Applied':'Head-level',type:'multi',q:`A leadership team identifies this issue: ${scenario} Which two responses show sound senior-management judgement?`,correct:[0,1],opts:[action,`Make the trade-off and success metric explicit before committing resources.`,...wrong.slice(0,2)],why:`The first action applies ${name}; the second makes its choice accountable. The volume-first option skips the customer problem, while copying a leader ignores strategic fit.`}
 ]; variants.forEach((v,vi)=>out.push({...v,id:`t${ti}c${ci}v${vi}`,topic:topic[0],concept:name,takeaway:action,number:out.length+1}));
}));return out}
const BANK=makeQuestions();
const verbal=[
'How would you move a steel portfolio from commodity comparison toward differentiated customer value without losing volume discipline?',
'How would you segment and prioritize a mixed portfolio of automotive OEMs, infrastructure accounts, fabricators and dealer-served SMEs?',
'When should a commercial leader defend market share, and when should they sacrifice volume to improve profitability?',
'How would you quantify and defend a value-based price premium for a technically superior industrial product?',
'What channel design would balance direct key-account control, distributor economics and digital convenience?',
'How would you distinguish brand awareness, customer-based brand equity and financial brand value in a leadership review?',
'What leading and lagging indicators belong on a Head of Marketing & Sales dashboard?',
'How would you diagnose whether a retention problem comes from value, service, relationship coverage or customer economics?',
'How would you align sales incentives with margin, mix, collections, retention and strategic-account development?',
'How should sustainability become customer value rather than a generic corporate claim?',
'How would you redesign the commercial operating model to sell solutions rather than products?',
'How would you allocate resources between a mature cash-generating line and uncertain value-added growth opportunities?'
];
const defaultState={answered:{},attempts:{},bookmarked:[],read:[],streak:0,bestStreak:0,sessionAnswered:0,sessionCorrect:0,theme:null,currentId:null,mode:'adaptive',topic:null,incognito:false,fullIndex:0,navCollapsed:false};
const storedState=JSON.parse(localStorage.getItem('marketSignalState')||'{}');
if(!storedState.bookmarked&&Array.isArray(storedState.flagged))storedState.bookmarked=storedState.flagged;
delete storedState.flagged;
let state={...defaultState,...storedState};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let current=null, locked=false;
function save(){localStorage.setItem('marketSignalState',JSON.stringify(state))}
function topicStats(){return TOPICS.map(t=>{const ids=BANK.filter(q=>q.topic===t[0]).map(q=>q.id), attempts=ids.reduce((n,id)=>n+(state.attempts[id]?.total||0),0), correct=ids.reduce((n,id)=>n+(state.attempts[id]?.correct||0),0);return{name:t[0],attempts,correct,rate:attempts?correct/attempts:0}})}
function candidatePool(){let p=BANK;if(state.mode==='topic'&&state.topic)p=p.filter(q=>q.topic===state.topic);if(state.mode==='sprint')p=p.filter(q=>!state.answered[q.id]);return p.length?p:BANK}
function chooseNext(forceTopic){if(state.mode==='full'&&!forceTopic)return BANK[state.fullIndex%BANK.length];let p=forceTopic?BANK.filter(q=>q.topic===forceTopic):candidatePool();const answeredCount=Object.keys(state.answered).length;let level=answeredCount<30?'Intermediate':answeredCount<120?'Applied':'Head-level';if(state.sessionCorrect/Math.max(1,state.sessionAnswered)>.78&&state.sessionAnswered>5)level='Head-level';const fresh=p.filter(q=>!state.answered[q.id]&&q.difficulty===level);const unseen=p.filter(q=>!state.answered[q.id]);const pool=fresh.length?fresh:unseen.length?unseen:p;return pool[Math.floor(Math.random()*pool.length)]}
function renderQuestion(q=chooseNext()){current=q;state.currentId=q.id;save();locked=false;$('#questionTag').textContent=q.topic.toUpperCase();$('#difficultyTag').textContent=q.difficulty.toUpperCase();$('#questionType').textContent=`${q.type==='multi'?'MULTIPLE ANSWERS':q.type==='truefalse'?'TRUE / FALSE':'SINGLE ANSWER'} · ${q.difficulty==='Head-level'?'STRATEGIC TRADE-OFF':'DECISION SCENARIO'}`;$('#questionText').textContent=q.q;$('#questionIndex').textContent=`Question ${String(BANK.indexOf(q)+1).padStart(3,'0')} of ${BANK.length}`;$('#multiHint').hidden=q.type!=='multi';$('#feedback').hidden=true;$('#checkAnswer').hidden=false;$('#checkAnswer').disabled=false;$('#nextQuestion').hidden=true;$('#copyStatus').textContent='';syncQuestionTools();
 $('#answers').innerHTML=q.opts.map((o,i)=>`<label class="answer ${q.type==='multi'?'multi':''}"><input type="${q.type==='multi'?'checkbox':'radio'}" name="answer" value="${i}"><span class="answer-key">${LETTERS[i]}</span><span class="answer-text">${o}</span></label>`).join('');
 $$('#answers input').forEach(input=>input.addEventListener('change',()=>{if(q.type!=='multi')$$('.answer').forEach(x=>x.classList.remove('selected'));input.closest('.answer').classList.toggle('selected',input.checked)}));updateStats()}
function checkAnswer(){if(locked)return next();const selected=$$('#answers input:checked').map(i=>+i.value);if(!selected.length){$('#answers').animate([{transform:'translateX(-5px)'},{transform:'translateX(5px)'},{transform:'none'}],{duration:220});return}locked=true;const right=selected.length===current.correct.length&&selected.every(i=>current.correct.includes(i));$$('.answer').forEach((el,i)=>{el.classList.add('locked');if(current.correct.includes(i))el.classList.add('correct');else if(selected.includes(i))el.classList.add('incorrect');el.querySelector('input').disabled=true});
 const recorded=!state.incognito;if(recorded){const prior=state.attempts[current.id]||{total:0,correct:0};state.attempts[current.id]={total:prior.total+1,correct:prior.correct+(right?1:0)};if(!state.answered[current.id]){state.answered[current.id]=right?'correct':'incorrect';state.sessionAnswered++;if(right)state.sessionCorrect++}state.streak=right?state.streak+1:0;state.bestStreak=Math.max(state.bestStreak,state.streak);save()}
 $('#feedback').classList.toggle('is-wrong',!right);$('#feedbackMark').textContent=right?'✓':'×';$('#feedbackTitle').textContent=state.incognito?(right?'Correct — not recorded.':'Incorrect — not recorded.'):(right?'Strong call.':'Reframe the decision.');$('#feedbackText').textContent=current.why;$('#conceptText').textContent=`${current.concept} — ${current.opts[current.correct[0]]}`;$('#takeawayText').textContent=current.takeaway;$('#feedback').hidden=false;$('#checkAnswer').hidden=true;$('#nextQuestion').hidden=false;updateStats();$('#feedback').scrollIntoView({behavior:'smooth',block:'nearest'});if(recorded&&state.sessionAnswered>0&&state.sessionAnswered%25===0)setTimeout(showSummary,450)}
function next(){if(state.mode==='full'){state.fullIndex=(BANK.indexOf(current)+1)%BANK.length;save()}renderQuestion()}
function syncFullBankNavigator(){const visible=state.mode==='full'&&$('#quizView').classList.contains('active');$('#fullBankNavigator').hidden=!visible;$('.topbar').classList.toggle('has-full-slider',visible);if(!visible)return;const position=(state.fullIndex%BANK.length)+1,progress=(position-1)/(BANK.length-1)*100;$('#fullBankSlider').value=position;$('#fullBankSlider').style.setProperty('--slider-progress',`${progress}%`);$('#fullBankPosition').textContent=`${String(position).padStart(3,'0')} / ${BANK.length}`}
function updateStats(){const count=Object.keys(state.answered).length;$('#topProgressText').textContent=`${count} / ${BANK.length}`;$('#topProgressFill').style.width=`${Math.round(count/BANK.length*100)}%`;$('#reviewCount').textContent=state.bookmarked.length;syncFullBankNavigator()}
function navigate(view){$$('.view,.nav-item').forEach(x=>x.classList.remove('active'));$(`#${view}View`).classList.add('active');$(`.nav-item[data-view="${view}"]`).classList.add('active');$('#progressButton').classList.toggle('active',view==='dashboard');if(view==='dashboard')renderDashboard();if(view==='overview')renderOverview();if(view==='review')renderReview();syncFullBankNavigator();window.scrollTo({top:0,behavior:'smooth'})}
function renderDashboard(){const count=Object.keys(state.answered).length,correct=Object.values(state.answered).filter(x=>x==='correct').length,stats=topicStats(),tried=stats.filter(s=>s.attempts>=3).sort((a,b)=>b.rate-a.rate);$('#dashAnswered').textContent=count;$('#dashAccuracy').textContent=count?`${Math.round(correct/count*100)}%`:'—';$('#bestTopic').textContent=tried[0]?.name||'Build baseline';$('#weakTopic').textContent=tried.at(-1)?.name||'Build baseline';$('#topicBars').innerHTML=stats.map(s=>`<div class="topic-row"><span>${s.name}</span><div class="bar"><i style="width:${Math.round(s.rate*100)}%"></i></div><b>${s.attempts?Math.round(s.rate*100)+'%':'—'}</b></div>`).join('');$('#verbalPrompts').innerHTML=verbal.slice(0,5).map(x=>`<li>${x}</li>`).join('')}
function renderOverview(filter=''){const term=filter.trim().toLowerCase(),status=$('#overviewStatus').value;const topics=TOPICS.map(topic=>{const questions=BANK.filter(q=>q.topic===topic[0]),readCount=questions.filter(q=>state.read.includes(q.id)).length,bookmarkCount=questions.filter(q=>state.bookmarked.includes(q.id)).length;return{topic,questions,readCount,bookmarkCount}}).filter(({topic,questions,readCount,bookmarkCount})=>{const matchesText=!term||topic[0].toLowerCase().includes(term)||topic[1].some(c=>`${c[0]} ${c[1]}`.toLowerCase().includes(term));const matchesStatus=status==='all'||status==='unread'&&readCount<questions.length||status==='read'&&readCount===questions.length||status==='bookmarked'&&bookmarkCount>0;return matchesText&&matchesStatus});$('#overviewResultCount').textContent=`${topics.length} topic${topics.length===1?'':'s'}`;$('#overviewGrid').innerHTML=topics.map(({topic:[name,concepts],questions,readCount,bookmarkCount})=>`<details class="overview-topic"><summary><div><h2>${name}</h2><span class="topic-meta">${questions.length} QUESTIONS · ${readCount} READ · ${bookmarkCount} BOOKMARKED</span></div><span class="select-chevron" aria-hidden="true">⌄</span></summary><div class="concept-map">${concepts.map(c=>`<article class="concept-card"><strong>${c[0]}</strong><p>${c[1]}</p></article>`).join('')}</div><div class="overview-actions"><button data-overview-topic="${name}">Practise privately →</button></div></details>`).join('');$$('[data-overview-topic]').forEach(button=>button.onclick=()=>{state.mode='topic';state.topic=button.dataset.overviewTopic;state.incognito=true;syncSessionControls();save();navigate('quiz');renderQuestion(chooseNext(state.topic))})}
function renderReview(){const items=state.bookmarked.map(id=>BANK.find(q=>q.id===id)).filter(Boolean);$('#reviewList').innerHTML=items.length?items.map(q=>`<article class="review-card"><div><span class="topic-tag">${q.topic.toUpperCase()} · ${q.difficulty.toUpperCase()} · ${state.read.includes(q.id)?'READ':'UNREAD'}</span><p>${q.q}</p></div><button data-review="${q.id}">Practise →</button></article>`).join(''):'<p class="empty">No bookmarks yet. Use the bookmark button beside any question number to save it here.</p>';$$('[data-review]').forEach(b=>b.onclick=()=>{navigate('quiz');renderQuestion(BANK.find(q=>q.id===b.dataset.review))})}
function showSummary(){const stats=topicStats().filter(s=>s.attempts).sort((a,b)=>b.rate-a.rate),score=Math.round(state.sessionCorrect/state.sessionAnswered*100);$('#summaryScore').textContent=`${state.sessionCorrect} / ${state.sessionAnswered} · ${score}%`;$('#strongList').innerHTML=(stats.slice(0,3).map(s=>`<li>${s.name} — ${Math.round(s.rate*100)}%</li>`).join('')||'<li>Keep building your baseline</li>');$('#weakList').innerHTML=(stats.slice(-3).reverse().map(s=>`<li>${s.name} — ${Math.round(s.rate*100)}%</li>`).join('')||'<li>No weak signal yet</li>');const offset=(state.sessionAnswered/25)%verbal.length;$('#summaryPrompts').innerHTML=[0,1,2,3,4].map(i=>`<li>${verbal[(offset+i)%verbal.length]}</li>`).join('');$('#summaryDialog').showModal()}
function syncQuestionTools(){const isRead=state.read.includes(current.id),isBookmarked=state.bookmarked.includes(current.id),readAction=isRead?'Mark question as unread':'Mark question as read',bookmarkAction=isBookmarked?'Remove bookmark':'Bookmark question';$('#readToggle').classList.toggle('active',isRead);$('#readToggle').setAttribute('aria-pressed',String(isRead));$('#readToggle').setAttribute('aria-label',readAction);$('#readToggle').dataset.tooltip=readAction;$('#readLabel').textContent=isRead?'Read':'Unread';$('#bookmarkButton').classList.toggle('active',isBookmarked);$('#bookmarkButton').setAttribute('aria-pressed',String(isBookmarked));$('#bookmarkButton').setAttribute('aria-label',bookmarkAction);$('#bookmarkButton').dataset.tooltip=bookmarkAction;$('#bookmarkLabel').textContent=isBookmarked?'Bookmarked':'Bookmark'}
function toggleRead(){const i=state.read.indexOf(current.id);i>=0?state.read.splice(i,1):state.read.push(current.id);save();syncQuestionTools()}
function toggleBookmark(){const i=state.bookmarked.indexOf(current.id);i>=0?state.bookmarked.splice(i,1):state.bookmarked.push(current.id);save();syncQuestionTools();updateStats()}
function buildAIContext(){const selected=$$('#answers input:checked').map(input=>LETTERS[Number(input.value)]),lines=[`I am preparing for a senior Head of Marketing & Sales interview using Kotler and Keller's Marketing Management.`,`Please explain the following question at senior-management depth. Distinguish the plausible options, show the managerial trade-offs, and apply it to a steel or industrial B2B context.`,``,`Topic: ${current.topic}`,`Difficulty: ${current.difficulty}`,`Format: ${current.type==='multi'?'Multiple answer':current.type==='truefalse'?'True/False':'Single answer'}`,`Question: ${current.q}`,`Options:`,...current.opts.map((option,i)=>`${LETTERS[i]}. ${option}`)];if(selected.length)lines.push(`My selected answer: ${selected.join(', ')}`);if(locked){lines.push(`Correct answer: ${current.correct.map(i=>LETTERS[i]).join(', ')}`,`Book explanation: ${current.why}`,`Interview takeaway: ${current.takeaway}`)}lines.push(``,`Help me understand the reasoning rather than merely restating the answer.`);return lines.join('\\n')}
async function copyAIContext(){const text=buildAIContext();try{if(navigator.clipboard?.writeText)await navigator.clipboard.writeText(text);else{const area=document.createElement('textarea');area.value=text;area.style.position='fixed';area.style.opacity='0';document.body.append(area);area.select();if(!document.execCommand('copy'))throw new Error('Copy failed');area.remove()}$('#copyStatus').textContent='AI context copied to clipboard.';$('#copyContextButton').classList.add('copied');setTimeout(()=>{$('#copyStatus').textContent='';$('#copyContextButton').classList.remove('copied')},1800)}catch{$('#copyStatus').textContent='Could not copy automatically. Check browser clipboard permission.'}}
function setTheme(theme){document.documentElement.dataset.theme=theme;state.theme=theme;$('#themeLabel').textContent=theme==='dark'?'Light appearance':'Dark appearance';save()}
$$('.nav-item').forEach(button=>button.onclick=()=>{navigate(button.dataset.view);closeTransientNavigation()});$('#progressButton').onclick=()=>{navigate('dashboard');closeTransientNavigation()};$('#checkAnswer').onclick=checkAnswer;$('#nextQuestion').onclick=next;$('#readToggle').onclick=toggleRead;$('#bookmarkButton').onclick=toggleBookmark;$('#copyContextButton').onclick=copyAIContext;$('#themeToggle').onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');$('#keyboardHelp').onclick=()=>$('#shortcutsDialog').showModal();$$('.dialog-close').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('.dialog-continue').onclick=()=>$('#summaryDialog').close();
$('#resetProgress').onclick=()=>{if(confirm('Clear all answers, accuracy, streaks, read statuses and bookmarks on this device?')){localStorage.removeItem('marketSignalState');state={...defaultState,answered:{},attempts:{},bookmarked:[],read:[]};syncSessionControls();syncChrome();renderQuestion();updateStats()}};
$('#topicSelect').innerHTML=TOPICS.map(t=>`<option>${t[0]}</option>`).join('');
function syncSessionControls(){const topicMode=state.mode==='topic';$('#modeSelect').value=state.mode;$('#topicSelect').value=state.topic||TOPICS[0][0];$('#topicSelect').disabled=!topicMode;$('#topicControl').hidden=!topicMode;$('#incognitoToggle').checked=Boolean(state.incognito);$('#incognitoBanner').hidden=!state.incognito;syncFullBankNavigator()}
syncSessionControls();
$('#modeSelect').onchange=e=>{state.mode=e.target.value;if(state.mode==='full')state.fullIndex=0;state.topic=state.mode==='topic'?$('#topicSelect').value:null;syncSessionControls();save();renderQuestion()};
$('#incognitoToggle').onchange=e=>{state.incognito=e.target.checked;syncSessionControls();save()};
$('#topicSelect').onchange=e=>{state.topic=e.target.value;save();renderQuestion()};
$('#overviewSearch').oninput=e=>renderOverview(e.target.value);$('#overviewStatus').onchange=()=>renderOverview($('#overviewSearch').value);
$('#fullBankSlider').oninput=e=>{state.fullIndex=Number(e.target.value)-1;renderQuestion(BANK[state.fullIndex])};
$('#startWeak').onclick=()=>{const weak=topicStats().filter(s=>s.attempts).sort((a,b)=>a.rate-b.rate)[0]?.name||TOPICS[0][0];state.mode='topic';state.topic=weak;syncSessionControls();save();navigate('quiz');renderQuestion(chooseNext(weak))};
const mobileQuery=matchMedia('(max-width: 900px)');
let activeDisclosure=null;
function syncChrome(){const mobile=mobileQuery.matches,navOpen=document.body.classList.contains('nav-open'),controlsOpen=document.body.classList.contains('controls-open'),backdrop=$('#navBackdrop');document.body.classList.toggle('sidebar-collapsed',!mobile&&Boolean(state.navCollapsed));$('#sidebar').inert=mobile&&!navOpen;$('#menuToggle').setAttribute('aria-expanded',String(mobile?navOpen:!state.navCollapsed));$('#controlsToggle').setAttribute('aria-expanded',String(controlsOpen));backdrop.hidden=!(navOpen||controlsOpen);backdrop.tabIndex=navOpen||controlsOpen?0:-1}
function closeTransientNavigation(restoreFocus=false){document.body.classList.remove('nav-open','controls-open');syncChrome();if(restoreFocus&&activeDisclosure)activeDisclosure.focus();activeDisclosure=null}
$('#menuToggle').onclick=()=>{if(mobileQuery.matches){const opening=!document.body.classList.contains('nav-open');document.body.classList.toggle('nav-open');activeDisclosure=opening?$('#menuToggle'):null;document.body.classList.remove('controls-open');syncChrome();if(opening)requestAnimationFrame(()=>$('.nav-item').focus())}else{state.navCollapsed=!state.navCollapsed;save();syncChrome()}};
$('#controlsToggle').onclick=()=>{const opening=!document.body.classList.contains('controls-open');document.body.classList.toggle('controls-open');activeDisclosure=opening?$('#controlsToggle'):null;document.body.classList.remove('nav-open');syncChrome();if(opening)requestAnimationFrame(()=>$('#modeSelect').focus())};
$('#navBackdrop').onclick=()=>closeTransientNavigation(true);
mobileQuery.addEventListener('change',()=>{closeTransientNavigation();syncChrome()});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&(document.body.classList.contains('nav-open')||document.body.classList.contains('controls-open')))closeTransientNavigation(true)});
$$('[data-tooltip][title]').forEach(element=>element.removeAttribute('title'));
syncChrome();
document.addEventListener('keydown',e=>{if($$('dialog[open]').length||e.target.matches('input,select,textarea'))return;if(e.key.toLowerCase()==='d'){navigate('dashboard');return}if(!$('#quizView').classList.contains('active'))return;if(['1','2','3','4'].includes(e.key)&&!locked){const input=$$('#answers input')[+e.key-1];if(input)input.click()}if(e.key==='Enter'){e.preventDefault();locked?next():checkAnswer()}if(e.key.toLowerCase()==='b')toggleBookmark();if(e.key.toLowerCase()==='r')toggleRead();if(e.key.toLowerCase()==='c')copyAIContext()});
const preferred=state.theme||(matchMedia('(prefers-color-scheme: light)').matches?'light':'dark');setTheme(preferred);renderQuestion(state.mode==='full'?chooseNext():state.currentId&&BANK.find(q=>q.id===state.currentId)||chooseNext());
